language: r
r:
  - release
  - devel
cache: packages
sudo: required

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
r_packages:
  - h5
  - readr
  - dplyr
  - stringr
  - tidyr
  - knitr
  - rmarkdown
  - ggplot2
  - scales

before_install:
  - wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz
  - tar -xzvf hdf5-1.10.1.tar.gz
  - cd hdf5-1.10.1
  - ./configure --prefix=/usr/local --enable-cxx
  - sudo make install
  - cd ..
