language: r
r:
  - release
  - devel
cache: packages
sudo: required

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
r_packages:
  - h5
  - readr
  - dplyr
  - stringr
  - tidyr
  - knitr
  - rmarkdown
  - ggplot2
  - scales

before_install:
  - sudo apt-get install libhdf5-dev
  - echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/hdf5.conf
  - sudo ldconfig
