language: r
r:
  - release
  - devel
cache: packages
sudo: required

env:
  global:
    - PKG_CFLAGS="-pedantic"
    - _R_CHECK_CRAN_INCOMING_=FALSE
    - ASAN="-fsanitize=address -fno-omit-frame-pointer"
    - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  matrix:
    - HDF5_VERSION=1.8.14
    - HDF5_VERSION=1.8.16
    - HDF5_VERSION=1.10.0-patch1
    - HDF5_VERSION=1.10.1

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling
r_packages:
 - readr
 - dplyr
 - stringr
 - tidyr
 - knitr
 - rmarkdown
 - ggplot2
 - scales
 - h5

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh
