language: r
r:
  - release
  - devel
sudo: required
cache: packages

# Be strict when checking our package
warnings_are_errors: true

# System dependencies for HTTP calling

r_packages:
  - readr
  - dplyr
  - stringr
  - tidyr
  - knitr
  - rmarkdown
  - ggplot2
  - scales
  - h5

before_install:
  - wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz
  - tar -xzf hdf5-1.10.1.tar.gz
  - cd hdf5-1.10.1
  - ./configure -q --prefix=/usr/local --enable-cxx --enable-build-mode=production 
  - sudo make install > file.log 2>&1 && echo OK || echo "Installation Failed!"
  - cd ..
  - sudo rm -rf hdf5-1.10.1
  - sudo rm -f hdf5-1.10.1.tar.gz
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
