```{r requirements, echo = FALSE, include = FALSE}
library(ggplot2)
library(dplyr)
library(stringr)
library(knitr)
plot.theme = list(
  theme_grey(base_size = 16),
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
)
```

# RAStestR Report

This is a basic RASTestR report for comparing outputs of a 
**new model `r label2`** to outputs of a **base model `r label1`**. 
The new model is *type `r type2`*  and the base model is 
*type `r type1`*  The data sources of the two models are listed below:
 - **Base:** `r file1`
 - **Compare**: `r file2`

The following sections are included in this report:

```{r print-section, echo = FALSE, results = "asis"}
cat(paste0(seq_along(childsections), ". ", childsections), sep = '\n')
```

```{r loop-children, echo = FALSE, include = FALSE}
out = NULL
for (section.label in childsections) {
  chunkfile = sectionchunk(section.label)
  out = c(out, knit_child(chunkfile))
}
```

```{r print-report, echo= FALSE, results = "asis"}
cat(out, sep= '\n\n')
```